### ISSUE TITLE
Unrolled Spin Loops

### ISSUE THREAD

**Issue by JackThomson2** [kprotty/usync#6]
Hey,

Great project, really interesting! I've been having a play with unrolling the spin loops to try and make it faster, and seem to have got there!

In one test it went from 1421 -> 2046 kHz! I have attached a godbolt link here to show the approach for unrolling. My tests had the cpu check in just removed it to clean up the outputted assembly.

https://rust.godbolt.org/z/MrrnqfoPP

I had to increase the number of pauses as the loop is now faster. The downsides are that the assembly is now slightly more, however if run with optimisation level S it removes the unrolling.

A couple of questions:

 1. What benchmark parameters are you mainly testing with? 
 2. Would you be interested in me creating a PR with it? 

Thanks Jack

**Comment by kprotty** [comment]
My first instinct is that this could be a case of optimizing for benchmarks while degrading efficiency in practical use. Could you list what benchmarks you ran and under what operating system? 

Generally, when testing if a spinning policy is worth it, I test both the mutex and rwlock combinations under the following parameters:

---

`N = 2 * n` where `n` = number of logical cpu cores. This tests:
- micro-contention (e.g. `2-4` threads)
- expected concurrency (e.g. `4-n` threads)
- extreme concurrency (e.g. `n-N` threads).

That last case is important as that tests the locks under over-subscription.
This is often where poorly scalable locks like spin-locks perform worse, especially when the critical sections are longer.

* `0:N:2 10 100`: 
Benchmark usage: small crit section, a bit of delay between attempts. 
Locks which aggresively avoid wakeups scale best in throughput here.

* `0:N:2 100 100`:
Rare but important usage: even but "lengthly" amount of time spent in and outside the lock.
The slightly longer critical sections show what happens when wake ups become more often

* `0:N:2 100 1000`:
Expected/optimistic usage: long times spent outside the lock.
At lower levels of concurrency, the results for all the locks should be similar. How it scales to higher concurrency levels matters here.

* `0:N:2 1000 10`:
Poor/unexpected usage: holding the lock for far too long when there's a ton of contention.
This forces past adaptive spinning and benches the thread queuing algorithm. Expect smaller throughput numbers and things like spinlocks to often suffer.

I'd like to explore more environments for that spinning approach before merging / considering a PR given its potential for code bloat and wasted cycles.

**Comment by JackThomson2** [comment]
Thanks for a very detailed reply

It did seem the initial approach I'd taken was working well for the specific benchmark I'd been using. I pulled the code back a bit and made it much closer to the current implementation. 

```rust
        match self.counter {
            1 => cpu_spin(5 << 1),
            2 => cpu_spin(5 << 2),
            3 => cpu_spin(5 << 3),
            4 => cpu_spin(5 << 4),
            _ => cpu_spin(5 << 5),
        }
```

5 was chosen here as with the current implementation there's 5 instructions per PAUSE, so in theory should match.

When running the different scenarios it matched with: `0:N:2 100 1000` and `0:N:2 1000 10`. But was faster for `0:N:2 100 100` and `0:N:2 10 100` 

I'm running this on an x86 macbook if thats helps

**Comment by thomcc** [comment]
Note that spinning to much can also *significantly* increase CPU usage (and the time is spent mostly doing nothing), so that should be taken in mind as well.

**Comment by JackThomson2** [comment]
I'm not too experienced with it and just playing really. But my naive thought process was the number of ASM instructions per pause cycle is the same in the second block I sent, just more of them are PAUSE rather than INC and JAs etc. Reading into PAUSE it looked to me it would actually reduce cpu usage and power usage. So was hoping it'd be more efficient.

**Comment by kprotty** [comment]
Slight correction in that the current implementation does `1 << 0..5` spins instead of `5 << 0..5` spins.

PAUSE *may* reduce power usage (although not by much it seems because the CPU remains in C0), but it doesn't reduce cpu usage; Its still taking up cpu cycles and thread quota time that could be used elsewhere. You can visually see it by running the benchmark with a spin-lock and looking at your task-viewer.

**Comment by JackThomson2** [comment]
Sorry, I probably didn't phrase it correctly but looking at the current implementation for each loops step the assembly is doing 5 ops per spin operation 

<img width="375" alt="image" src="https://user-images.githubusercontent.com/10991628/161136091-da29f6e1-bd23-45a9-867b-20a1ec6e772d.png">

So by doing 5 pause instructions it should in theory be spinning the same amount. And I was under the impression that it may help a hyper threaded cpu core. I'll close it for now, doesn't look like my theory makes sense. Thanks for the insight all!
